---
Name: mysite
After: 'framework/*','cms/*', 'mysite/*'
---
Member:
  extensions:
    - PresentationMemberExtension
    - MemberTokenProvider
    - SummitAttendeeMemberExtension
MemberTokenProvider:
  token_expire: 3600
Director:
  rules:
    'presentations/api/v1': 'PresentationAPI'
    'trackchairs/api/v1': 'TrackChairAPI'
    'presentations/authenticate': 'PresentationAPITokenGenerator'
    'summit-login': 'SummitSecurity'
    'summit-admin': 'SummitAppAdminController'
PresentationCategory:
  extensions:
    - JSONable
PresentationSpeaker:
  extensions:
    - JSONable
PresentationTopic:
  extensions:
    - JSONable
SummitPresentationComment:
  extensions:
    - JSONable
Summit:
  extensions:
    - JSONable
SummitTrackChair:
  extensions:
    - JSONable
SummitCategoryChange:
  extensions:
    - JSONable    
Presentation:
  extensions:
    - Sluggable
    - JSONable
  status_options:
    - Received
    - In community voting
    - Being reviewed by track chairs
    - accepted
    - not accepted
    - accepted as an alternate
BootstrapMemberLoginForm:
  extensions:
    - BootstrapLoginFormExtension